Repository fect-org/fect, pull requests merged in 2021-07, with the labels that each got.

#36 docs(icons): support search and update icons version
  docs/example/icons/component/icons.vue
  docs/zh-cn/themes/icons.mdx
  package-lock.json
  package.json
Labels: documentation, feature

#37 refactor(docs):use vue
  _page/ActiveCate/activecate.common.less
  _page/ActiveCate/index.jsx
  _page/Anchor/anchor.common.less
  _page/Anchor/anchor.icon.jsx
  _page/Anchor/index.jsx
  _page/Attributes/attributes.title.jsx
  _page/Attributes/attributes.title.less
  _page/Attributes/index.jsx
  _page/CodeShow/code.component.jsx
  _page/CodeShow/code.component.less
  _page/CodeShow/code.preview.jsx
  _page/CodeShow/code.preview.less
  _page/CodeShow/code.render.jsx
  _page/CodeShow/code.title.jsx
  _page/CodeShow/code.title.less
  _page/CodeShow/code.wrapper.jsx
  _page/CodeShow/index.jsx
  _page/Layout/index.jsx
  _page/Logo/index.jsx
  _page/SiderBar/index.jsx
  _page/SiderBar/sidebar.item.jsx
  _page/SiderBar/sidebar.item.less
  _page/SiderBar/sidebar.mobile.less
  _page/SiderBar/tabbar.mobile.jsx
  _page/SiderBar/widgets.jsx
  _page/SiderBar/widgets.less
  _page/index.js
  _page/install.js
  page/ActiveCate/index.vue
  page/Anchor/index.vue
  page/Attributes/attributes-title.vue
  page/Attributes/index.vue
  page/CodeShow/animation.less
  page/CodeShow/code-component.vue
  page/CodeShow/code-preview.vue
  page/CodeShow/code.css
  page/CodeShow/index.vue
  page/CodeShow/type.ts
  page/Layout/index.vue
  page/Layout/type.ts
  page/Logo/index.vue
  page/SiderBar/index.vue
  page/SiderBar/tabbar-mobile.vue
  page/SiderBar/type.ts
  page/SiderBar/widgets.vue
  page/index.ts
  page/install.ts
  src/App.vue
  src/main.ts
  src/shims-vue.d.ts
  tsconfig.json
Labels: documentation, perf

#44 docs(update): update version
  docs/zh-cn/quickStart/install.md
  docs/zh-cn/quickStart/into.md
Labels: documentation

#45 fix(component): fix error name cause install error
  package.json
  packages/utils/create/index.ts
Labels: bug

#46 <docs>: edit the import path of main.css
  README.md
Labels: documentation

#47 chore(script): remove useless script and supplement docs
  docs/zh-cn/quickStart/install.md
  docs/zh-cn/quickStart/introduce.md
  src/components.js
Labels: documentation

#49 feat(tab): support props disabled
  docs/example/tabs/disabled.vue
  docs/zh-cn/components/tabs.md
  packages/tabs/index.tsx
  vetur/attributes.json
  vetur/tags.json
Labels: feature

#55 fix(loading): fix loading style error and docs
  docs/example/pagination/custom.vue
  packages/loading/__tests__/__snapshots__/index.spec.js.snap
  packages/loading/index.less
  packages/loading/index.tsx
Labels: bug
