Repository fect-org/fect, pull requests merged in 2021-08, with the labels that each got.

#57 chore(dep): update eslint version and perf useState
  package-lock.json
  package.json
  packages/utils/useState/useState.ts
Labels: perf

#58 test(unit): improve unit testing of some components
  packages/breadcrumbs-item/__tests__/__snapshots__/index.spec.js.snap
  packages/breadcrumbs-item/__tests__/index.spec.js
  packages/capacity/__tests__/__snapshots__/index.spec.js.snap
  packages/capacity/__tests__/index.spec.js
  packages/col/__tests__/__snapshots__/index.spec.ts.snap
  packages/col/__tests__/__snapshots__/index.spec.tsx.snap
  packages/col/__tests__/index.spec.tsx
  packages/progress/__tests__/index.spec.js
  packages/row/__tests__/index.spec.ts
  packages/spacer/__tests__/__snapshots__/index.spec.tsx.snap
  packages/spacer/__tests__/index.spec.tsx
  packages/switch/__tests__/index.spec.js
Labels: test:unit

#59 test(unit): retest the unit test of skeleton and tabs
  jest.config.js
  packages/skeleton/__tests__/__snapshots__/index.spec.js.snap
  packages/skeleton/__tests__/__snapshots__/index.spec.tsx.snap
  packages/skeleton/__tests__/index.spec.js
  packages/skeleton/__tests__/index.spec.tsx
  packages/tab/__tests__/__snapshots__/index.spec.js.snap
  packages/tab/__tests__/index.spec.js
  packages/tabs/__tests__/__snapshots__/index.spec.tsx.snap
  packages/tabs/__tests__/index.spec.js
  packages/tabs/__tests__/index.spec.tsx
Labels: test:unit

#62 perf(tabs): useState replace ref
  docs/example/tabs/divider.vue
  packages/tab/index.tsx
  packages/tabs/index.tsx
Labels: perf

#68 fix(modal): when load modal component the Page will be lock
  packages/modal/__tests__/__snapshots__/index.spec.ts.snap
  packages/modal/__tests__/index.spec.ts
  packages/modal/modal.tsx
  packages/modal/type.ts
  vetur/attributes.json
  vetur/tags.json
Labels: bug

#74 perf(drawer) : Optimize drawer animation
  packages/drawer/__tests__/__snapshots__/index.spec.ts.snap
  packages/drawer/drawer-wrapper.tsx
  packages/drawer/index.less
  packages/drawer/index.tsx
  packages/drawer/style.ts
  packages/index.ts
  packages/modal/modal-wrapper.tsx
  packages/teleport/index.tsx
  packages/utils/styles/index.css
  scripts/collect.js
Labels: perf

#75 chore(changelog): update changelog
  CHANGELOG.md
Labels: documentation

#78 refacotr (build) : reafcotr build script
  .gitignore
  .travis.yml
  build/README.md
  build/bundler.d.ts
  build/bundler.js
  build/clean-build.d.ts
  build/clean-build.js
  build/clean-dir.js
  build/compiler-component.js
  build/compiler-entry.js
  build/compiler-js.d.ts
  build/compiler-js.js
  build/compiler-umd.js
  build/constant.d.ts
  build/constant.js
  build/environment.js
  build/gen-style-deps.d.ts
  build/gen-style-deps.js
  build/gen-style.js
  build/index.js
  build/utils.js
  package-lock.json
  package.json
  scripts/tsconfig.json
Labels: bug, perf

#79 perf(build): change code style remove func setEnv & cleanBuild in index.js
  build/bundler.d.ts
  build/bundler.js
  build/index.js
Labels: perf

#81 test(breadcrumbs): update breadcrumbs unit test case with ts
  package-lock.json
  packages/breadcrumbs/__tests__/__snapshots__/index.spec.js.snap
  packages/breadcrumbs/__tests__/__snapshots__/index.spec.ts.snap
  packages/breadcrumbs/__tests__/index.spec.ts
Labels: perf
