Repository fect-org/fect, pull requests merged in 2022-05, with the labels that each got.

#223 [Refactor](useTheme): singleton pattern
  packages/vue/src/utils/composables/use-theme.ts
Labels: feature, perf

#227 fix(form): modify modelValue can't trigger update
  packages/vue/src/checkbox-group/checkbox-group.tsx
  packages/vue/src/checkbox/checkbox.tsx
  packages/vue/src/radio-group/radio-group.tsx
  packages/vue/src/radio/radio.tsx
Labels: bug

#229 style: clean code & fix loading css err
  packages/vue/src/button/__tests__/__snapshots__/index.spec.tsx.snap
  packages/vue/src/loading/__tests__/__snapshots__/index.spec.ts.snap
  packages/vue/src/loading/__tests__/index.spec.ts
  packages/vue/src/loading/index.less
  packages/vue/src/loading/loading-circle.tsx
  packages/vue/src/loading/loading.tsx
  packages/vue/src/loading/props.ts
Labels: bug

#230 [Fix]: Slider trigger a darg event it both trigger click event.
  packages/vue/src/slider/index.less
  packages/vue/src/slider/slider.tsx
Labels: bug, feature

#231 feat(utils): add make func & clean code
  packages/vue/src/loading/loading.tsx
  packages/vue/src/pagination/pagination-pages.tsx
  packages/vue/src/rating/rating.tsx
  packages/vue/src/spinner/spinner.tsx
  packages/vue/src/swipe/swipe.tsx
  packages/vue/src/utils/format/arrary.ts
Labels: feature

#233 [Perf]: component typings & fix select component multiple mode style err
  packages/vue-hooks/package.json
  packages/vue/package.json
  packages/vue/src/avatar-group/avatar-context.ts
  packages/vue/src/badge-anchor/badge-context.ts
  packages/vue/src/breadcrumbs/breadcrumbs-context.ts
  packages/vue/src/button-group/button-group-context.ts
  packages/vue/src/button/__tests__/__snapshots__/index.spec.tsx.snap
  packages/vue/src/checkbox-group/checkbox-context.ts
  packages/vue/src/checkbox-group/interface.ts
  packages/vue/src/collapse-group/collapse-context.ts
  packages/vue/src/collapse-group/interface.ts
  packages/vue/src/form-item/form-item.tsx
  packages/vue/src/form/form-context.ts
  packages/vue/src/form/form.tsx
  packages/vue/src/form/interface.ts
  packages/vue/src/grid-group/grid-context.ts
  packages/vue/src/input/__tests__/__snapshots__/index.spec.ts.snap
  packages/vue/src/modal/modal-context.ts
  packages/vue/src/pagination/pagination-context.ts
  packages/vue/src/radio-group/interface.ts
  packages/vue/src/radio-group/radio-context.ts
  packages/vue/src/rating/__tests__/__snapshots__/index.spec.tsx.snap
  packages/vue/src/row/interface.ts
  packages/vue/src/row/layout-context.ts
  packages/vue/src/select/__tests__/__snapshots__/index.spec.ts.snap
  packages/vue/src/select/index.less
  packages/vue/src/select/interface.ts
  packages/vue/src/select/props.ts
  packages/vue/src/select/select-context.ts
  packages/vue/src/select/select.tsx
  packages/vue/src/skeleton/skeleton-context.ts
  packages/vue/src/swipe/interface.ts
  packages/vue/src/swipe/swipe-context.ts
  packages/vue/src/tabs/interface.ts
  packages/vue/src/tabs/tabs-context.ts
  packages/website/package.json
Labels: bug, feature
